import 'package:bookstore_app/features/splash/ui/splash_screen.dart';
import 'package:bookstore_app/routes/app_router.dart';
import 'package:bookstore_app/routes/app_routes.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:supabase_flutter/supabase_flutter.dart'; // Add this import
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase (for Firestore)
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  
  // Initialize Supabase (for image storage)
  await Supabase.initialize(
    url: 'https://nmxsedfpkkgygouqjmyx.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5teHNlZGZwa2tneWdvdXFqbXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTUyODUsImV4cCI6MjA3MDU3MTI4NX0.8BcB7AAXTcf5WIRgJskZgN0dEAWYmmY2eo3rw-JC-C0',
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bookify',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const SplashScreen(),
      initialRoute: AppRoutes.splash,
      onGenerateRoute: AppRouter.generateRoute,
    );
  }
}